[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  timeout = { default = "30s" }

[[redirects]]
  force = true
  from = "/node/express/*"
  status = 200
  to = "/.netlify/functions/express/:splat"

[[redirects]]
  force = true
  from = "/node/function/*"
  status = 200
  to = "/.netlify/functions/function/:splat"

[[redirects]]
  force = true
  from = "/node/function1/*"
  status = 200
  to = "/.netlify/functions/function1/:splat"

[[redirects]]
  force = true
  from = "/node/handle/*"
  status = 200
  to = "/.netlify/functions/handle/:splat"

[[redirects]]
  force = true
  from = "/node/function2/*"
  status = 200
  to = "/.netlify/functions/function2/:splat"

[[redirects]]
  force = true
  from = "/node/function2-background/*"
  status = 200
  to = "/.netlify/functions/function2-background/:splat"

[[redirects]]
  force = true
  from = "/node/function3/*"
  status = 200
  to = "/.netlify/functions/function3/:splat"

[[redirects]]
  force = true
  from = "/node/wait/*"
  status = 200
  to = "/.netlify/functions/wait/:splat"

[[redirects]]
  force = true
  from = "/node/unwait/*"
  status = 200
  to = "/.netlify/functions/unwait/:splat"

[[redirects]]
  force = true
  from = "/node/wait1/*"
  status = 200
  to = "/.netlify/functions/wait1/:splat"

[[redirects]]
  force = true
  from = "/node/unwait1/*"
  status = 200
  to = "/.netlify/functions/unwait1/:splat"

[[edge_functions]]
  path = "/edge/function"
  function = "function"

[[edge_functions]]
  path = "/edge/handle"
  function = "handle"
