[build]
  command = "echo No build"
  functions = "functions"

[[redirects]]
  force = true
  from = "/api/express/*"
  status = 200
  to = "/.netlify/functions/express/:splat"

[[redirects]]
  force = true
  from = "/api/function/*"
  status = 200
  to = "/.netlify/functions/function/:splat"

[[redirects]]
  force = true
  from = "/api/handle/*"
  status = 200
  to = "/.netlify/functions/handle/:splat"

[[edge_functions]]
  path = "/edge/function"
  function = "function"

[[edge_functions]]
  path = "/edge/handle"
  function = "handle"